"""Single-image scene captioning wrapped as a :class:`~app.agents.tools.base.Tool` (brief §2A, §17).

The query-free counterpart to :class:`~app.agents.tools.vqa.VqaTool`: it takes one optical scene and
returns a descriptive caption of its land cover, built by :func:`app.services.captioning.describe_scene`
from the deterministic classifier's measured fractions — never a language-model generation. Like
:class:`~app.agents.tools.landcover.LandCoverTool` it needs no query, so :meth:`preprocess` carries
nothing extra in :attr:`Prepared.context`.

Confidence is the evidence-based report from :func:`app.services.confidence.for_landcover` (§27): the
caption describes exactly what the classification found, so the classification's confidence is the
caption's. Registers at :attr:`~app.agents.tools.base.ToolTier.CLASSICAL`.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from ...core.errors import ErrorCode, ValidationError
from ...core.types import InputMode, Modality, QueryTask
from ...geospatial.validate import assess_quality
from ...services import confidence
from ...services.captioning import describe_scene
from .base import Prepared, Tool, ToolContext, ToolResult, ToolTier

if TYPE_CHECKING:
    from ...services.captioning import SceneCaption


class CaptioningTool(Tool):
    """Describe the land cover of a single optical scene as a short caption."""

    task: ClassVar[QueryTask] = QueryTask.CAPTIONING
    name: ClassVar[str] = "captioning-landcover-cv"
    tier: ClassVar[ToolTier] = ToolTier.CLASSICAL
    summary: ClassVar[str] = (
        "Single-image scene captioning: a deterministic descriptive caption of a scene's land "
        "cover, naming the dominant class and the measured share of every class present — filled "
        "from classifier fractions, not generated by a language model."
    )

    # A caption describes one scene.
    supported_modes: ClassVar[tuple[InputMode, ...]] = (InputMode.SINGLE_OPTICAL,)
    min_images: ClassVar[int] = 1
    max_images: ClassVar[int] = 1
    required_modalities: ClassVar[frozenset[Modality]] = frozenset({Modality.OPTICAL})

    def validate_input(self, ctx: ToolContext) -> None:
        ctx.expect_count(1, self.task)
        raster = ctx.rasters[0]
        if raster.modality is Modality.SAR:
            raise ValidationError(
                "Scene captioning describes land cover, which needs an optical (multispectral) "
                "image — a single SAR image carries no spectral land-cover signal. Use SAR "
                "analysis for radar imagery.",
                code=ErrorCode.WRONG_MODALITY,
                context={"tool": self.name, "modality": raster.modality.value},
            )

    def preprocess(self, ctx: ToolContext) -> Prepared:
        raster = ctx.rasters[0]
        return Prepared(rasters=[raster], quality=assess_quality(raster))

    def predict(self, prepared: Prepared) -> SceneCaption:
        return describe_scene(prepared.rasters[0])

    def explain(self, raw: SceneCaption) -> list[str]:
        return list(raw.evidence)

    def postprocess(self, raw: SceneCaption, prepared: Prepared) -> ToolResult:
        report = confidence.for_landcover(raw.landcover, prepared.quality)
        return self.build_result(
            answer=raw.caption,
            data=raw.to_dict(),
            confidence=report,
            evidence=self.explain(raw),
            warnings=raw.warnings,
            raw=raw,
        )
