import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import { getAnalysis } from '@/services/api'
import { buildReportModel } from '@/lib/report-model'
import type { ReportBlock, ReportModel } from '@/lib/report-model'
import { renderReportHtml, escapeHtml } from '@/lib/report-html'
import { ReportDocument } from '@/components/report/report-document'

const GENERATED_AT = '2026-08-27T10:00:00.000Z'

async function modelFor(id: string): Promise<ReportModel> {
  const result = await getAnalysis(id)
  return buildReportModel(result, GENERATED_AT)
}

function findingsSection(model: ReportModel) {
  const section = model.sections.find((s) => s.id === 'findings')
  expect(section).toBeDefined()
  return section!
}

const isCallout = (b: ReportBlock): b is Extract<ReportBlock, { kind: 'callout' }> =>
  b.kind === 'callout'
const isFields = (b: ReportBlock): b is Extract<ReportBlock, { kind: 'fields' }> =>
  b.kind === 'fields'
const isTable = (b: ReportBlock): b is Extract<ReportBlock, { kind: 'table' }> => b.kind === 'table'

describe('buildReportModel', () => {
  it('summarises a land-cover analysis with measured metrics', async () => {
    const model = await modelFor('SAT-2026-000101')
    expect(model.id).toBe('SAT-2026-000101')
    expect(model.withheld).toBe(false)
    expect(model.unreliable).toBe(false)
    expect(model.caveat).toBeNull()

    const section = findingsSection(model)
    expect(section.title).toMatch(/land-cover/i)

    const fieldLabels = section.blocks.filter(isFields).flatMap((b) => b.fields.map((f) => f.label))
    expect(fieldLabels).toContain('Class separability')

    const classTable = section.blocks
      .filter(isTable)
      .find((b) => /per-class area/i.test(b.table.caption ?? ''))
    expect(classTable).toBeDefined()
    expect(classTable!.table.rows.some((r) => /bare soil/i.test(r.class))).toBe(true)
  })

  it('never asserts an unreliable object count for grounding (§28)', async () => {
    const model = await modelFor('SAT-2026-000103')
    const callouts = findingsSection(model).blocks.filter(isCallout)

    // The withheld-count case emits a warning callout, not a confident "Count".
    expect(
      callouts.some((c) => c.tone === 'warning' && /count not reportable/i.test(c.title ?? '')),
    ).toBe(true)
    expect(callouts.some((c) => c.tone === 'success' && c.title === 'Count')).toBe(false)

    // Any figure it does surface is explicitly framed as *not* a reliable count.
    const warning = callouts.find((c) => c.tone === 'warning')!
    expect(warning.body).toMatch(/not a reliable/i)
  })

  it('carries the evidence-based confidence disclaimer (§27)', async () => {
    const model = await modelFor('SAT-2026-000101')
    expect(model.disclaimer).toMatch(/not generated by a language model/i)
    const confidence = model.sections.find((s) => s.id === 'confidence')
    expect(confidence).toBeDefined()
    const factorTable = confidence!.blocks.filter(isTable).find((b) => b.table.columns.length > 0)
    expect(factorTable).toBeDefined()
  })
})

describe('renderReportHtml', () => {
  it('produces a self-contained document with the id, answer and disclaimer', async () => {
    const model = await modelFor('SAT-2026-000101')
    const html = renderReportHtml(model)
    expect(html.startsWith('<!doctype html')).toBe(true)
    expect(html).toContain('SAT-2026-000101')
    expect(html).toContain(escapeHtml(model.answer))
    expect(html).toContain('not generated by a language model')
    // Standalone: styles are inline, no external stylesheet or script.
    expect(html).not.toMatch(/<link[^>]+stylesheet/i)
    expect(html).not.toMatch(/<script/i)
  })

  it('routes artifact images through the injected resolver', async () => {
    const model = await modelFor('SAT-2026-000101')
    const html = renderReportHtml(model, () => 'data:image/png;base64,STUB')
    expect(html).toContain('src="data:image/png;base64,STUB"')
  })

  it('escapes HTML metacharacters', () => {
    expect(escapeHtml(`<b>"x" & 'y'>`)).toBe('&lt;b&gt;&quot;x&quot; &amp; &#39;y&#39;&gt;')
  })
})

describe('ReportDocument', () => {
  it('renders the report with id, query and answer', async () => {
    const model = await modelFor('SAT-2026-000101')
    render(<ReportDocument model={model} />)
    expect(screen.getByText('SAT-2026-000101')).toBeInTheDocument()
    expect(screen.getByText(model.query)).toBeInTheDocument()
    expect(screen.getByText(model.answer)).toBeInTheDocument()
    // The evidence-based disclaimer appears (confidence note + footer).
    expect(screen.getAllByText(/not generated by a language model/i).length).toBeGreaterThan(0)
  })
})
